/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as UnprotectedRouteImport } from './routes/_unprotected'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedRoomRouteImport } from './routes/_protected/room'
import { Route as UnprotectedAboutRouteImport } from './routes/_unprotected/about'
import { Route as UnprotectedContactRouteImport } from './routes/_unprotected/contact'
import { Route as UnprotectedHomeRouteImport } from './routes/_unprotected/home'
import { Route as AuthIndexRouteImport } from './routes/auth/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const UnprotectedRoute = UnprotectedRouteImport.update({
  id: '/_unprotected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRoomRoute = ProtectedRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => ProtectedRoute,
} as any)
const UnprotectedAboutRoute = UnprotectedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => UnprotectedRoute,
} as any)
const UnprotectedContactRoute = UnprotectedContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => UnprotectedRoute,
} as any)
const UnprotectedHomeRoute = UnprotectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => UnprotectedRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/room': typeof ProtectedRoomRoute
  '/about': typeof UnprotectedAboutRoute
  '/contact': typeof UnprotectedContactRoute
  '/home': typeof UnprotectedHomeRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/room': typeof ProtectedRoomRoute
  '/about': typeof UnprotectedAboutRoute
  '/contact': typeof UnprotectedContactRoute
  '/home': typeof UnprotectedHomeRoute
  '/auth': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_unprotected': typeof UnprotectedRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/room': typeof ProtectedRoomRoute
  '/_unprotected/about': typeof UnprotectedAboutRoute
  '/_unprotected/contact': typeof UnprotectedContactRoute
  '/_unprotected/home': typeof UnprotectedHomeRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dashboard' | '/room' | '/about' | '/contact' | '/home' | '/auth/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/room' | '/about' | '/contact' | '/home' | '/auth'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_unprotected'
    | '/_protected/dashboard'
    | '/_protected/room'
    | '/_unprotected/about'
    | '/_unprotected/contact'
    | '/_unprotected/home'
    | '/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  UnprotectedRoute: typeof UnprotectedRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unprotected': {
      id: '/_unprotected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnprotectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/room': {
      id: '/_protected/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof ProtectedRoomRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_unprotected/about': {
      id: '/_unprotected/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof UnprotectedAboutRouteImport
      parentRoute: typeof UnprotectedRoute
    }
    '/_unprotected/contact': {
      id: '/_unprotected/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof UnprotectedContactRouteImport
      parentRoute: typeof UnprotectedRoute
    }
    '/_unprotected/home': {
      id: '/_unprotected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof UnprotectedHomeRouteImport
      parentRoute: typeof UnprotectedRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedRoomRoute: typeof ProtectedRoomRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedRoomRoute: ProtectedRoomRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface UnprotectedRouteChildren {
  UnprotectedAboutRoute: typeof UnprotectedAboutRoute
  UnprotectedContactRoute: typeof UnprotectedContactRoute
  UnprotectedHomeRoute: typeof UnprotectedHomeRoute
}

const UnprotectedRouteChildren: UnprotectedRouteChildren = {
  UnprotectedAboutRoute: UnprotectedAboutRoute,
  UnprotectedContactRoute: UnprotectedContactRoute,
  UnprotectedHomeRoute: UnprotectedHomeRoute,
}

const UnprotectedRouteWithChildren = UnprotectedRoute._addFileChildren(
  UnprotectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  UnprotectedRoute: UnprotectedRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
